export const APP_DATA_RUNTIME_SET_TOKEN = 'APP_DATA_RUNTIME_SET_TOKEN';
export const APP_DATA_RUNTIME_SET_CONFIG = 'APP_DATA_RUNTIME_SET_CONFIG';
export const APP_DATA_SET_LANGUAGE = 'APP_DATA_SET_LANGUAGE';
export const APP_DATA_SET_USER = 'APP_DATA_SET_USER';
export const APP_LINGUI_SET_CATALOG = 'APP_LINGUI_SET_CATALOG';
