export default {
    USE_EVERYTHING_FOR_TOKEN: null,
    USE_COOKIE_FOR_TOKEN: false,
    USE_BEARER_FOR_TOKEN: true,
    SEND_USERNAME_PASSWORD_FIELDS_ERROR: true,
    UPLOAD_ADMIN: true,
    UPLOAD_AUTH: true,
    REBUILD_STATUS_ERROR: -1,
    REBUILD_STATUS_SUCCESS: 0,
    REBUILD_STATUS_COPY_SRC_DIR: 1,
    REBUILD_STATUS_NPM_INSTALL: 2,
    REBUILD_STATUS_NPM_BUILD_UPDATE: 3,
    REBUILD_STATUS_NPM_UPDATE_COPY: 4,
    REBUILD_STATUS_SETUP_ALL: 5
};
