stages:
  - build
  - test
  - deploy

image: ubuntu

before_script:
  - apt-get update 
  - apt-get install -y nodejs
  - apt-get install -y npm


build_zoya:
  stage: build
  script:
    - echo "This job builds something fantastic"
    - npm install
    - npm run config
