# syntax=docker/dockerfile:1

FROM node:latest

WORKDIR /zoia

COPY ["package.json", "package-lock.json*", "package-core.json*", "./"]
RUN npm i

COPY . .

RUN npm run config
RUN npm run build-dev

RUN apt-get update && apt-get upgrade -y
RUN npm install pm2 -g

CMD [ "pm2-runtime", "npm", "--", "start" ]