# Triggers pipeline in GitLab, creates release if pipeline was successful

name: CI master trigger GitLab

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Trigger gitlab
        run: curl --request POST "https://gitlab.com/api/v4/projects/19934840/trigger/pipeline?token=${GITLAB_TOKEN}&ref=master"
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'master' }}
