# Triggers pipeline in GitLab, creates release if pipeline was successful

name: CI master trigger GitLab

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
    - name: Trigger gitlab
      run: python trigger_gitlab.py
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_READ_TOKEN: ${{ secrets.GITLAB_TOKEN }}  
          
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'master' }}
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: 12.x

     - name: Install
       run: npm ci

     - name: Release
       run: npx semantic-release
