# Triggers pipeline in GitLab, creates release and deploys Demo Zoia to production if pipeline was successful 

name: CI for master branch, triggers tests in GitLab, creates release, deploys Demo Zoia to production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
        
    - name: Send commit and trigger tests on Gitlab
      run: python /home/runner/work/zoia/zoia/.github/workflows/trigger_gitlab.py 
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_READ_TOKEN: ${{ secrets.GITLAB_READ_TOKEN }}
        GITLAB_BRANCH: "pull_request"   
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}  
        COMMIT_BRANCH: "master"   
          
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: 12.x

     - name: Install
       run: npm ci

     - name: Update Zoia version using semantic versioning plugin
       run: |
         npm install @semantic-release/git @semantic-release/changelog -D 
         npx semantic-release --debug --plugins "@semantic-release/commit-analyzer","@semantic-release/release-notes-generator","@semantic-release/changelog","@semantic-release/npm","@semantic-release/git"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  
  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: [build, release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
        
    - name: Trigger deployment of Demo Zoia in Gitlab
      run: python /home/runner/work/zoia/zoia/.github/workflows/trigger_gitlab.py
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_READ_TOKEN: ${{ secrets.GITLAB_READ_TOKEN }}    
        GITLAB_BRANCH: "deploy_zoia_to_prod"   
        COMMIT_MESSAGE: "Deploying Demo Zoia to production after successfully testing pull request"  
        COMMIT_BRANCH: "master" 
